# Site Settings
locale                   : "en"
title                    : "A quiddity yet to come"
title_separator          : "-"
name                     : "Bas Nijholt"
url                      : "http://www.nijholt.org"
repository               : "basnijholt/nijholt.org"
words_per_minute         : 200


# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-84702771-1"


# Site Author
author:
  name             : "Bas Nijholt"
  avatar           : "profile.jpg"
  bio              : "A 26 yo PhD student in computational quantum mechanics that likes photography, traveling, physics, machine learning, and programming in Python."
  location         : "Rotterdam, The Netherlands"
  email            : "basnijholt@gmail.com"
  500px            : "basnijholt"
  github           : "basnijholt"
  google_scholar   : "nIO4EK4AAAAJ&hl"
  instagram        : "bnijholt"
  lastfm           : "bas116"
  linkedin         : "basnijholt"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - deploy.sh
  - compile.sh
  - CNAME
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Amsterdam"


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# 500px
500px_consumer_key_file: 500px-consumer-key


# jekyll-scholar
scholar:
  style: _bibliography/authors.csl
  source: ./_bibliography
  bibliography_template: bib

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
